//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3lab_komanda32 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_3lab_komanda32.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Id mismatch.
        /// </summary>
        internal static string AddressIdMismatch {
            get {
                return ResourceManager.GetString("AddressIdMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address not found, Id =.
        /// </summary>
        internal static string AddressIdNotFound {
            get {
                return ResourceManager.GetString("AddressIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Id mismatch.
        /// </summary>
        internal static string BusinessIdMismatch {
            get {
                return ResourceManager.GetString("BusinessIdMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business not found, Id = .
        /// </summary>
        internal static string BusinessIdNotFound {
            get {
                return ResourceManager.GetString("BusinessIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID mismatch.
        /// </summary>
        internal static string EmployeeIDMisMatch {
            get {
                return ResourceManager.GetString("EmployeeIDMisMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee not found, Id = .
        /// </summary>
        internal static string EmployeeIdNotFound {
            get {
                return ResourceManager.GetString("EmployeeIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating new business record.
        /// </summary>
        internal static string ErrCreatingBusiness {
            get {
                return ResourceManager.GetString("ErrCreatingBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating new employee record.
        /// </summary>
        internal static string ErrCreatingEmployee {
            get {
                return ResourceManager.GetString("ErrCreatingEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating new order record.
        /// </summary>
        internal static string ErrCreatingOrder {
            get {
                return ResourceManager.GetString("ErrCreatingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating new order confirmation record.
        /// </summary>
        internal static string ErrCreatingOrderConfirm {
            get {
                return ResourceManager.GetString("ErrCreatingOrderConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating new payment record.
        /// </summary>
        internal static string ErrCreatingPayment {
            get {
                return ResourceManager.GetString("ErrCreatingPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating new privelege record.
        /// </summary>
        internal static string ErrCreatingPrivilege {
            get {
                return ResourceManager.GetString("ErrCreatingPrivilege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating new product record.
        /// </summary>
        internal static string ErrCreatingProduct {
            get {
                return ResourceManager.GetString("ErrCreatingProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating new reservation record.
        /// </summary>
        internal static string ErrCreatingReservation {
            get {
                return ResourceManager.GetString("ErrCreatingReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating new service record.
        /// </summary>
        internal static string ErrCreatingService {
            get {
                return ResourceManager.GetString("ErrCreatingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting record.
        /// </summary>
        internal static string ErrDataDelete {
            get {
                return ResourceManager.GetString("ErrDataDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating data.
        /// </summary>
        internal static string ErrDataUpdate {
            get {
                return ResourceManager.GetString("ErrDataUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving data from the database.
        /// </summary>
        internal static string ErrRetrieveFromDB {
            get {
                return ResourceManager.GetString("ErrRetrieveFromDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Id mismatch.
        /// </summary>
        internal static string OrderIdMismatch {
            get {
                return ResourceManager.GetString("OrderIdMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order not found, Id = .
        /// </summary>
        internal static string OrderIdNotFound {
            get {
                return ResourceManager.GetString("OrderIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Id mismatch.
        /// </summary>
        internal static string PaymentIdMismatch {
            get {
                return ResourceManager.GetString("PaymentIdMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment not found, Id = .
        /// </summary>
        internal static string PaymentIdNotFound {
            get {
                return ResourceManager.GetString("PaymentIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found, Id =.
        /// </summary>
        internal static string ProductIdNotFound {
            get {
                return ResourceManager.GetString("ProductIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation Id mismatch.
        /// </summary>
        internal static string ReservationIdMismatch {
            get {
                return ResourceManager.GetString("ReservationIdMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation not found, Id = .
        /// </summary>
        internal static string ReservationIdNotFound {
            get {
                return ResourceManager.GetString("ReservationIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Id mistmatch.
        /// </summary>
        internal static string ServiceIdMismatch {
            get {
                return ResourceManager.GetString("ServiceIdMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service not found, Id = .
        /// </summary>
        internal static string ServiceIdNotFound {
            get {
                return ResourceManager.GetString("ServiceIdNotFound", resourceCulture);
            }
        }
    }
}
